### ISSUE TITLE
sendMessage invoked but no messageCallback defined

### ISSUE THREAD

**Issue by jcsomac** [caffeinalab/ti.goosh#23]
i am getting this error when i receive a notification

<img width="763" alt="screen shot 2016-10-09 at 1 57 06 pm" src="https://cloud.githubusercontent.com/assets/2636175/19223094/a861ae22-8e2c-11e6-9463-c866880c615d.png">

My code is:

<img width="578" alt="screen shot 2016-10-09 at 2 28 50 pm" src="https://cloud.githubusercontent.com/assets/2636175/19223098/bef024fc-8e2c-11e6-9751-b8fd783126a4.png">

Thanks in advance.
Titanium SDK : 5.5.1

**Comment by progress44** [comment]
What's the status of the app when this happens? Is it in the background, closed or open? Are you using the latest version of ti.goosh?

**Comment by jcsomac** [comment]
Hi... the app is open, and yes, i am using 1.6.1 version of the module.

**Comment by progress44** [comment]
Does this happen always?

**Comment by jcsomac** [comment]
Yeap... i am trying right now, cleaning the project, and rebuilding it again.. and is the same..

**Comment by jcsomac** [comment]
Confirmed one more time.
and for the record, the notification arrives. but i want to do something when that happend.

![d2491553-ad1d-45df-9bca-f6345ec45bc6](https://cloud.githubusercontent.com/assets/2636175/19223159/5944d7d6-8e2e-11e6-8116-0b8fe7e95591.jpg)

i want to insert the notification in a table to create a "notification counter".
But with no "callback" event, there is no way to doit.

Thanks for the help

**Comment by progress44** [comment]
Yeah I understand. The callback is supposed to work. That's why we put it there. We're going to investigate the issue and see why this is happening.

**Comment by jcsomac** [comment]
hi again, i dont know if this can help you to help me, but i tried the old module caffeine.gcm and i got the same error message.

<img width="889" alt="screen shot 2016-10-09 at 2 59 23 pm" src="https://cloud.githubusercontent.com/assets/2636175/19223257/fd695524-8e30-11e6-96f1-787c58e1ade4.png">

maybe is some bad android configuration ?
thanks in advance.

**Comment by kopiro** [comment]
Are you calling you `iniciarApp` on boot?

**Comment by jcsomac** [comment]
hi kopiro, yeap, iniciarapp() is a function, and i called just after some vars set.
The code you see, is the app.js
thanks.

**Comment by kopiro** [comment]
Hi @jcsomac, maybe is not related, but you should never use the `Ti.App.[VAR]` form to store global objects.

From Titanium SDK starter tutorial:

Many users attempt to add to the Ti namespace as a means to persist data across contexts, extend / override native methods, etc. This can sometimes work but is very unreliable for the following reasons:

The Titanium end objects are really not true JavaScript objects. They are proxy representations of native operating system components. As such, they are constructed to pass through properties and method invocations. Your extensions could conflict with native functionality or interfere with proper operation of the proxy objects.
Sometimes you might be able to store things on the namespace but it's not changeable (i.e. an array stored on the namespace might not be able to be modified - mutable, etc.). Other-times your stored objects will be completely null.
Since this isn't an approved way of storing anything, there's no guarantee it will work in future releases of Titanium.
As a rule do not add to, or extend via the prototype, any object or module in the Titanium namespace. If you want to extend a core part of the Titanium API you should build a native module to accomplish this. If you're just looking for an extendible JS namespace, create your own (i.e. {{var MyApp={} }}).

Could you just try to write:

`require('ti.goosh').registerForPushNotifications`

**Comment by jcsomac** [comment]
Thanks Kopiro, and yes, this is old code and i am changing all that bad practices...
The problem persist when i try:

`require('ti.goosh').registerForPushNotifications`

but thanks anyhow..

**Comment by jcsomac** [comment]
hi guys... any news ? sugestions ?

**Comment by kopiro** [comment]
Could you post an entire log of `adb logcat | grep goosh` with boot + notification?

**Comment by jcsomac** [comment]
Sorry @kopiro how can i do that ?

**Comment by progress44** [comment]
@jcsomac just open a terminal window and run the code `adb logcat | grep goosh`

**Comment by jcsomac** [comment]
`BEM $ adb logcat | grep goosh`
`bash: adb: command not found`

it was executed in the root folder of the project.

**Comment by progress44** [comment]
run it as `android_sdk/platform-tools/adb logcat | grep goosh`  where android_sdk is the path to your sdk

**Comment by kopiro** [comment]
@jcsomac ?

**Comment by jcsomac** [comment]
Sorry i was on vacations...
here is the output:

platform-tools $ ./adb logcat | grep goosh
D/PMS     (  849): acquireWL(21a1b2de): PARTIAL_WAKE_LOCK  wake:com.bebesetmamans.forum/ti.goosh.IntentService 0x1 21357 10160 null
D/ti.goosh.IntentService(21357): Push notification received from: 713904143143
D/ti.goosh.IntentService(21357): Notification key : google.sent_time => 1476888270165 (java.lang.Long)
D/ti.goosh.IntentService(21357): Notification key : data => {"badge":1,"data":{"parent":"9565","child":"9621"},"alert":"Une maman vient de répondre à votre question al reves !","sound":"default","force_show_in_foreground":true,"vibrate":true,"tag":"APP","id":76763,"only_alert_once":false,"title":"Réponse du Forum BébésetMamans"} (java.lang.String)
D/ti.goosh.IntentService(21357): Notification key : google.message_id => 0:1476888270182359%54275acff9fd7ecd (java.lang.String)
D/ti.goosh.IntentService(21357): Notification key : collapse_key => do_not_collapse (java.lang.String)
E/ti.goosh.TiGooshModule(21357): sendMessage invoked but no messageCallback defined
D/PMS     (  849): releaseWL(21a1b2de): PARTIAL_WAKE_LOCK  wake:com.bebesetmamans.forum/ti.goosh.IntentService 0x1 null

**Comment by kopiro** [comment]
Could you try to do a full reinstall of app?

**Comment by jcsomac** [comment]
hi @kopiro, you
mean the titanium studio? or the android app?

**Comment by kopiro** [comment]
The android app.

**Comment by jcsomac** [comment]
And that's it !!!
Worked like magic....
Is there any explanaition about this ?

**Comment by kopiro** [comment]
Magic! :)
Anyway, I think something related to Android cache, but I don't really know.

**Comment by GerbenHofman** [comment]
A full re-install of my app also fixed: Sending event: exception on thread: AsyncTask #1 msg:java.lang.NullPointerException.
