### ISSUE TITLE
Question on remoteNotificationsEnabled on second app load

### ISSUE THREAD

**Issue by mikefogg** [caffeinalab/ti.goosh#30]
Quick question on the `remoteNotificationsEnabled` method.

On first app load when I get the token initially everything works great. The `remoteNotificationsEnabled` code works and will return true if I accept it. Once I close the app, on initialization when I use that to check to see if I should request push or not I get:

```
[INFO] :   TiGoosh.remoteNotificationsEnabled false
[INFO] :   TiGoosh.remoteDeviceUUID dgpX***PJ22M
```

Because I'm getting the device token, shouldn't `remoteNotificationsEnabled` be true? Looking over the source code it seems like it's only being set in the `registerForPushNotifications` success and failure callbacks.

So the question is, is remoteNotificationsEnabled really only supposed to be used AFTER firing `registerForPushNotifications` during that specific app load, and not between app loads?

Is it possible to create a method that verifies that 1) There is a `DeviceUUID` AND they have enabled push notifications (something like https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()).

**Comment by progress44** [comment]
Hi @mikefogg, the `remoteNotificationsEnabled` property is supposed to be be used to indicate whether the `registerForPushNotifications` method has been called or not. This means that it is behaving as it is meant to be. 
I looked at the Android API you provided, and it is only available in API 19 and above. Before that it always returns true so I don't think it's reliable enough. I'll mirror the method anyway. 
If you want to check the device token there already exists a method for that `getRemoteDeviceUUID` if it returns the token, hypothetically the notifications are enabled.
It is best practice to call `registerForPushNotifications` on each app launch because the device token could be updated at any time for various reasons
