### ISSUE TITLE
failed: dlopen failed: could not load library "libstlport_shared.so"

### ISSUE THREAD

**Issue by shinyste** [caffeinalab/ti.goosh#33]
As per title, when compiling my project with the appcelerator sdk 6.0.1 GA and 6.0.0 GA I encounter this error on the app startup
failed: dlopen failed: could not load library "libstlport_shared.so" needed by "libti.goosh.so"; caused by library "libstlport_shared.so" not found

**Comment by gstreetmedia** [comment]
Same thing with 6.1.X. Why isn't anything with TI + Android easy.

**Comment by progress44** [comment]
Hi @gstreetmedia can you tell us more about your app such as other modules you might be using, ti.goosh version, device model and make. We've tested ti.goosh with Titanium 6.0 and it worked fine.

**Comment by shinyste** [comment]
I have tested it with ti.facebook module and ti.map. With both I had the same issue

**Comment by progress44** [comment]
Ok, try checking the android sdk. Maybe it is missing some files.

**Comment by gstreetmedia** [comment]
I've disabled all plugins with exception of ti.goosh. Same result.

**Comment by gstreetmedia** [comment]
Could you add a copy of your .classpath file to the Repo?  Trying to get this module setup to build locally to help track down the problem.

**Comment by progress44** [comment]
You should be able to build the module as is. No other files are necessary

**Comment by gstreetmedia** [comment]
Recompiling the module against the latest 6.1.X seems to have solved this issue. I can't be sure if that was the fix or changing from

`architectures: armeabi armeabi-v7a x86`

to 

`architectures: armeabi-v7a x86`

was the solve. 

I did see the compiler sub in libstdc++ rather than the aformentioned missing "libstlport". 

I'm not sure if this a change at the NDK level or something else. 

Now I just have to figure out how to deal with the latest ti.map demanding a much newer version of the Google Play services.

**Comment by progress44** [comment]
Since you have so many problems with the modules, I really think there's a problem with your system configuration. What's the error you're having exactly? Can you paste it here?

**Comment by gstreetmedia** [comment]
I think I've worked through all the issues I was having. 

The first issue @shinyste opened this thread with "libstlport_shared.so" missing seemed to be resolved through recompiling the module against 6.1.X which fortunately contains a fix for duplicate entries [https://github.com/caffeinalab/ti.goosh/issues/29](url) 

The second issue I had is that the version of the Google Play services used in the latest Ti.Map uses

`import com.google.android.gms.maps.model.MapStyleOptions`

MapStyleOptions isn't available in version 8487000 of Google Play Services (as used by ti.goosh).  The fix was to remove that class + references from the latest Ti.Map and recompiled against 8487000.

Is there anything special about 8487000 as it relates to Ti.Goosh?  Backwards compatibility or anything like that?

**Comment by shinyste** [comment]
@gstreetmedia i had the same issue with the duplicated entries and i fixed it modifing the map jar (changing it to a zip, removing the readme and changing it back to jar) and after that i had no issue about the duplicated entries and the map module.
I can't get around the libstlport_shared.so error, do you mind sharing both the recompiled modules?

@progress44 to do some extra test i tried to do a clean installation of the android sdk and appcelerator sdk and update to the last jdk and still i have the libstlport_shared.so (tested with appcelerator sdk 6.0.0 GA, 6.0.1 GA and 6.1.0.v20170103080657 with other modules (ti.facebook and ti.map) or alone

**Comment by progress44** [comment]
I could reproduce the problem. Checking it out now

**Comment by netoramalho** [comment]
Same problem here

**Comment by progress44** [comment]
It happens because I built the module using SDK 5.5.1 although making the changes required for SDK 6.0. SDK 6.0 doesn't make use of `libstl_shared` anymore, in fact it is excluded because it is replaced by `libc++_shared`. The problem now is that I'm not being able to build the module using either SDK 6.0 or SDK 6.1.

**Comment by kopiro** [comment]
Could you try the latest build? https://github.com/caffeinalab/ti.goosh/releases/tag/v1.7.3

**Comment by netoramalho** [comment]
@kopiro Thank you! It worked
