### ISSUE TITLE
App crashes when receiving Push (FCM)

### ISSUE THREAD

**Issue by nuborian** [caffeinalab/ti.goosh#35]
Hi,

since FCM is "the future" I think we need a solution for this, so we can work with it :)

If i send a test notification over FCM my app crashes.

`[ERROR] :  TiApplication: (AsyncTask #3) [56387,57328] Sending event: exception on thread: AsyncTask #3 msg:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonObject.has(java.lang.String)' on a null object reference; Titanium 6.0.1,2016/12/19 16:51,undefined
[ERROR] :  TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonObject.has(java.lang.String)' on a null object reference
[ERROR] :  TiApplication: 	at ti.goosh.IntentService.parseNotification(IntentService.java:122)
[ERROR] :  TiApplication: 	at ti.goosh.IntentService.onMessageReceived(IntentService.java:54)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)`

Not sure how to set the "alert" object, since there is no such input on the fcm page. Just Keypairs. Any help would be great.

**Comment by progress44** [comment]
Try a payload as in the example I just committed here https://github.com/caffeinalab/ti.goosh/commit/37c9ce7cc0686c7fdc2fffb3ff248a3f76223c85

The module expects a `data` property and all the other properties to be in it therefore if you don't set it the app crashes because it tries to read `data` as an object. Firebase supports the data property so as long as you use it this way it works. You can keep using the default Firebase properties such as `title` but they're not considered at all by the module.
