### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by AppWerft** [caffeinalab/ti.goosh#74]
I see little improvements and tried to compile the sources. In this moduel are a jar, which version of googfle-play-services? the main problem is GcmListenerService. In which package? I cannot resolve it. 

Remark: compiling with 11.0.4 only works with SDK6.2.0 (new methods of appcompatactivity)

**Comment by progress44** [comment]
Google play services jar we're using at the moment is the one [here](https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars). I've noticed GPS version is crucial because some functions don't exist in older versions. 
If you have a solution for 6.2.0 that works, we can test it and roll out a major release setting SDK 6.2.0 as the required sdk. 
We're also trying to switch to FCM but it's been a bit challenging
