### ISSUE TITLE
Can't create custom google-play-service

### ISSUE THREAD

**Issue by DouglasHennrich** [caffeinalab/ti.goosh#85]
I'm trying to follow the instructions from here:
https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars

But I can't create my custom google play services since newer versions of google play doesn't have .jar files, only .aar

Someone can help me or create a stripped new google-play-services+analytics+maps ?

Thanks

**Comment by max1020** [comment]
are you using  version 3.0.1? did you see this: https://github.com/caffeinalab/ti.goosh/issues/80#issuecomment-331915885

**Comment by progress44** [comment]
As @max1020 suggests, you should be able to use the module by using just the necessary `.aar` files. The ones included in the repository.

**Comment by m1ga** [comment]
try these libs: http://www.migaweb.de/libs.zip
(remove the existing once).

working for me in combination with ti.maps 3.3.1

**Comment by lawjeremy** [comment]
I am unable to get 3.0.0 working with Ti.GA. Am I still supposed to replace the .jar files in the Ti.GA module?

**Comment by lawjeremy** [comment]
I am unable to get 3.0.0 working with Ti.GA. Am I still supposed to replace the .jar files in the Ti.GA module?

**Comment by progress44** [comment]
Since the use of .aar files, the proguard method doesn't work. As a temporary fix you can use `ti.ga` by leaving the analytics file file in ti.ga and removing play-services-base jar. Use the latest ti.ga as it should have the most recent google play services version.
This is a dirty fix but it works. Same goes for `ti.map` or other modules. Just remove duplicated libraries such as google play services
